packaging_format = 2

id = "diacamma"
name = "Diacamma"

description.en = "Management application for volunteers (association, condominium)"
description.fr = "Application de gestion pour les bénévoles (association, copropriété)"

version = "25.08.15.12~ynh1"

maintainers = ["Laurent Gay"]

[upstream]
license = " GPL-3.0-or-later"
website = "https://www.diacamma.org"
demo = "https://asso.diacamma.org"
code = "https://github.com/Diacamma2"
admindoc = "https://asso.diacamma.org/Docs"

[integration]
yunohost = ">= 12.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/diacamma"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.lct_appli]
    ask.en = "Application"
    ask.fr = "Application"
    help.en = "What application do you want to install?"
    help.fr = "Quelle application voulez-vous installer ?"
    type = "select"
    choices.asso = "Diacamma Asso"
    choices.syndic = "Diacamma Syndic"
    default = "asso"
    
    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    help.en = "This language will be used in the software installation"
    help.fr = "Cette langue sera utiliser dans l'installation du logiciel"
    type = "select"
    choices = ["fr","en"]
    default = "fr"

    [install.archivedir]
    ask.en = "Archive directory"
    ask.fr = "Répertoire d'archive"
    help.en = "Directory where are storaged Diacamma archives (disabled if empty)"
    help.fr = "Répertoire où sont stocker les archives Diacamma (désactivé si vide)"
    type = "path"
    optional = true
    default = ""

    [install.archivereadonly]
    ask.en = "Archive read-only"
    ask.fr = "Archive en lecture seul"
    help.en = "If checked, it will be impossible to create or import new archives"
    help.fr = "Si coché, il sera impossible de créer ou d'importer de nouvelles archives"
    type = "boolean"
    default = false
    
    [install.develop]
    ask.en = "Use the development version"
    ask.fr = "Utiliser la version de développement"
    help.en = "Facility will use 'https://pypi.diacamma.org' as repository"
    help.fr = "L'installation utilisera 'https://pypi.diacamma.org' comme dépot"
    type = "boolean"
    default = false

[resources]

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    admin.show_tile = false
    admin.allowed = "admins"

    [resources.ports]
    
    [resources.apt]
    packages = "libxml2-dev,libxslt-dev,libjpeg-dev,libfreetype6,libfreetype6-dev,zlib1g-dev,libpq-dev,python3-full,python3-pip,python3-dev,python3-tk,python3-pil,python3-venv,build-essential,pkg-config,postgresql,jq"

    [resources.database]
    type = "postgresql"

