#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

ynh_backup "$install_dir"

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP THE DATABASE
#=================================================
ynh_print_info "Backing up the postgresql database..."

ynh_psql_dump_db > dbbackup.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
