#!/bin/bash

# This is the tutorial version of the app.
# It contains extra commands to explain what should be done in case you want to adjust some part of the script.
# Once you are done, you may remove them.

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Stopping a service..."

ynh_systemctl --action=stop

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Updating Diacamma configuration..."

pushd $install_dir
ynh_config_add --template="extra_diacamma.json" --destination="/tmp/extra.json"
sed -i "s|$old_domain|$new_domain|g" /tmp/extra.json
if [ $archivereadonly -eq 1 ]
then
    sed -i 's|"BACKUP_READONLY": false,|"BACKUP_READONLY": true,|g' /tmp/extra.json
fi
if [ "$path" == "/" ]
then
    sed -i "/USE_X_FORWARDED_HOST/d" /tmp/extra.json 
    sed -i "/FORCE_SCRIPT_NAME/d" /tmp/extra.json 
    sed -i "/USE_X_FORWARDED_HOST/d" $install_dir/inst-${app}/settings.py 
    sed -i "/FORCE_SCRIPT_NAME/d" $install_dir/inst-${app}/settings.py
fi
extra_json=$(jq -c . /tmp/extra.json)
venv/bin/lucterios_admin.py modif -n inst-${app} -e ''$extra_json''
popd

update_software

refresh_collect

#=================================================
# START SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Starting a service..."

ynh_systemctl --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app" --last