#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

install_in_venv

pushd $install_dir
ynh_config_add --template="extra_diacamma.json" --destination="/tmp/extra.json"
if [ "$path" == "/" ]
then
    sed -i "/USE_X_FORWARDED_HOST/d" /tmp/extra.json 
    sed -i "/FORCE_SCRIPT_NAME/d" /tmp/extra.json 
fi
if [ "$archivedir" != '' ]
then
    mkdir -p $archivedir
    chmod ogu+rw $archivedir
fi
if [ $archivereadonly -eq 1 ]
then
    sed -i 's|"BACKUP_READONLY": false,|"BACKUP_READONLY": true,|g' /tmp/extra.json
fi
extra_json=$(jq -c . /tmp/extra.json)
venv/bin/lucterios_admin.py add -n inst_${app} -p "${APPLITYPE}" -m "${MODULES}" -d "${DATABASE}" -e ''$extra_json''
popd

refresh_collect

check_params

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to ${app}..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a log dir
mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown -R $app:www-data /var/log/$app/

# Create a dedicated service
ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting app's service..."

# Start a systemd service
ynh_systemctl --action=start

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of ${app} completed"
