#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers


#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

install_in_venv

ynh_restore "$install_dir/manage_inst-${app}.py"
ynh_restore "$install_dir/inst-${app}"

chmod -R ogu+rw "$install_dir/inst-${app}"
chmod ogu+x "$install_dir/inst-${app}"

#=================================================
# RESTORE SUPERVISOR CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

# This should be a symetric version of what happens in the install script

ynh_config_add_nginx

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================

ynh_script_progression "Restoring the PostgreSQL database..."

# Restore dump
ynh_psql_db_shell < dbbackup.sql

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Reload & prepare the app ..."

pushd $install_dir
venv/bin/lucterios_admin.py modif -n inst-${app} -d "${DATABASE}"
popd

update_software

refresh_collect

check_params

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_config_add_systemd

ynh_systemctl --action=reload

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "bin list = $(ls -la $install_dir/venv/bin)"
ynh_print_info "pip = $($install_dir/venv/bin/pip list)"

ynh_script_progression "Restoration completed for $app"
