#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Stopping a service..."

# check if upgrade and supervisor used before
if [ -f "/etc/supervisor/conf.d/${app}.conf" ]
then
    # Remove supervisor
    supervisorctl stop ${app}
    supervisorctl remove ${app}
    ynh_safe_rm "/etc/supervisor/conf.d/${app}.conf"
    supervisorctl reread
    
    # Create a log dir
    mkdir -p /var/log/$app
    touch /var/log/$app/$app.log
    chown -R $app:www-data /var/log/$app/

    # Create a dedicated service
    ynh_config_add_systemd
fi

ynh_systemctl --action=stop

#=================================================
# UPDATE DIACAMMA
#=================================================
ynh_script_progression "Updating Diacamma..."

update_software

refresh_collect

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# START SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Starting a service..."

ynh_systemctl --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"