#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STOP SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Stopping a service..."

ynh_systemctl --action=stop

#=================================================
# UPDATE DIACAMMA
#=================================================
ynh_script_progression "Updating Diacamma..."

update_software

refresh_collect

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# START SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Starting a service..."

ynh_systemctl --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"